// Code generated by command: go run asm.go -out sum.s -stubs sum.go. DO NOT EDIT.

#include "textflag.h"

// func Vectors(input []int64) int64
// Requires: AVX, AVX2
TEXT ·Vectors(SB), NOSPLIT, $0-32
	MOVQ input_base+0(FP), AX
	MOVQ input_len+8(FP), CX
	XORQ DX, DX
	XORQ BX, BX

	// If we can't use two YMM vectors (inputLen < 8), fallback to a scalar sum.
	CMPQ CX, $0x08
	JL   scalar_loop

	// Otherwise keep adding YMM vectors in the loop.
	// Y0 = input[0:4]
	VMOVDQU (AX), Y0

	// loopEnd = inputLen - (inputLen % 4)
	MOVQ CX, DX
	ANDQ $-4, DX

vector_loop:
	ADDQ    $0x00000004, BX
	CMPQ    DX, BX
	JLE     vector_loop_end
	VMOVDQU (AX)(BX*8), Y1
	VPADDQ  Y0, Y1, Y0
	JMP     vector_loop

vector_loop_end:
	// Horizontal reduction.
	VEXTRACTI128 $0x01, Y0, X1
	VPADDQ       X0, X1, X0
	VPSRLDQ      $0x08, X0, X1
	VPADDQ       X0, X1, X0
	VMOVQ        X0, DX
	VZEROUPPER

scalar_loop:
	// Summarize what we couldn't with SIMD.
	// for i; i < inputLen; i++
	CMPQ CX, BX
	JLE  scalar_loop_end
	ADDQ (AX)(BX*8), DX
	INCQ BX
	JMP  scalar_loop

scalar_loop_end:
	MOVQ DX, ret+24(FP)
	RET
